# cluster:
#   name: elk_local
# discovery:
#   zen:
#     minimum_master_nodes: 1
#     ping:
#       unicast:
# #         hosts: [ 'elasticsearch' ]
# path:
#   logs: /var/log/elasticsearch
#   data: /var/data/elasticsearch
  
# network:
#   host: ${ES_NETWORK_HOST}
# node:
#   data: true
#   master: true
#   name: ${HOSTNAME}